### ISSUE TITLE
Attribute tags not working (?)

### ISSUE THREAD

**Issue by nitnelave** [libregraph/lico#127]
I'm the maintainer of LLDAP, and a user came to me trying to use OCIS, which uses lico for the LDAP IDP.

They were trying to set the `IDP_LDAP_UUID_ATTRIBUTE_TYPE=text` env variable, but it didn't have the expected effect: instead of requesting the text version of the UUID, it requested both the `uuid` attribute and the `text` attribute (which doesn't exist).

The expected format for an attribute tag would be `uuid;text`.

I tried to trace it through the code, but I don't understand very well how you use that type attribute. After it's set (e.g. https://github.com/libregraph/lico/blob/0a498c48948e0a8566fa32f3f1d1b9b6d4195b95/identifier/backends/ldap/ldap.go#L85 ), I couldn't see other references to it specifically. However, I see in several places that you iterate through the attributes to write the values (e.g.  https://github.com/libregraph/lico/blob/0a498c48948e0a8566fa32f3f1d1b9b6d4195b95/identifier/backends/ldap/ldap.go#L630). That's going to completely dissociate the `uuid_type` from the `uuid` attribute, and just add a new attribute `text` or `binary`. Am I reading this wrong?

**Comment by rhafer** [comment]
> They were trying to set the `IDP_LDAP_UUID_ATTRIBUTE_TYPE=text` env variable, but it didn't have the expected effect: instead of requesting the text version of the UUID,

I think this is a missunderstanding of what `IDP_LDAP_UUID_ATTRIBUTE_TYPE` actually does. `IDP_LDAP_UUID_ATTRIBUTE_TYPE` in ocis basically sets `LDAP_UUID_ATTRIBUTE_TYPE` in lico. `LDAP_UUID_ATTRIBUTE_TYPE`.

The setting is purely about how lico interprets values of the uuid attribute (defined in `LDAP_UUID_ATTRIBUTE`). It is not supposed to add any LDAP Attribute Options  (like `;binary` or `;text`)   to the search request (AFAIK).
For details see, this where the `"%s_type"` value is used again:

https://github.com/libregraph/lico/blob/1e9a82b7d0eceb0fb0deddec2477ee51ab2d4474/identifier/backends/ldap/ldap.go#L120

> it requested both the `uuid` attribute and the `text` attribute (which doesn't exist).

This is a bug, I think.

> The expected format for an attribute tag would be `uuid;text`.

No. I don't think so. Are  there a actually LDAP server that support Attribute Options like `text` on a wider range of Attribute Type.

**Comment by longsleep** [comment]
If I read the code correctly it seems that we fetch a `uuid_text` or `uuid_binary` attribute (based on the value of `LDAP_UUID_ATTRIBUTE_TYPE`) for no reason. While this should be fixed I don't see how this can cause a problem? The LDAP server simply won't return this attribute if it does not exist.

I think we have no direct support for LDAP attribute options as of now. 

If the LDAP server returns a requested attribute name with tags in the response, it might be possible to map the default `uuid` attribute name to `uuid;text` with a configuration like so: `LDAP_UUID_ATTRIBUTE="uuid;text"`.

What is the problem with the `uuid` in the first place? The goal for `LDAP_UUID_ATTRIBUTE_TYPE` is to deal with the cases there the LDAP server returns `uuid` as binary (either some binary or as uuid bytes) as internally lico requires the uuid as string value.

**Comment by nitnelave** [comment]
The behavior that I saw was that it was requesting the "text" (or "binary") attribute.

It's not a problem _per se_, as you said, the server will just not return the attribute if it doesn't exist, it's just a surprising behavior. In our case I think that leaving the env variable empty didn't request the attribute? Not sure about that (it's not my setup, I can't test things).

If you don't want to support attribute tags, no worries. It was just my guess as to the intention of the env variable. LLDAP doesn't actually support them, so it's easier for me :D

No, not a show-stopper bug by far, but I thought you'd want to know since requesting the extra attribute is not intended.

**Comment by rhafer** [comment]
> The behavior that I saw was that it was requesting the "text" (or "binary") attribute.

Yes, that is a bug. (As I said)

**Comment by longsleep** [comment]
All right, but how can this happen @rhafer - will you make a fix?



> If you don't want to support attribute tags, no worries. It was just my guess as to the intention of the env variable. LLDAP doesn't actually support them, so it's easier for me :D

The question is more: do we need to support attribute tags for a valid production scenario?

**Comment by rhafer** [comment]
> All right, but how can this happen

Because the `LDAP_UUID_ATTRIBUTE_TYPE` is just added to the `ldapAttributeMapping` map with the  `"_type"`  string appended. The functions using `ldapAttributeMapping` would need to ignore keys ending in `"_type"`. E.g. the `attributes()` method:

https://github.com/libregraph/lico/blob/master/identifier/backends/ldap/ldap.go#L88

and `newLDAPUser`:

https://github.com/libregraph/lico/blob/master/identifier/backends/ldap/ldap.go#L106

I think putting that setting into the ldapAttributeMapping map was not a particular good idea.

> @rhafer - will you make a fix?

I can't promise yet. But let's see if I can squeeze it in somehow. Good thing is that this does not really break anything. It's mostly an annoyance.

**Comment by rhafer** [comment]
> The question is more: do we need to support attribute tags for a valid production scenario?

No. I don't think that support for "tags" (or attribute options as they are called in the RFCs IIRC) is needed anywhere in lico.

**Comment by longsleep** [comment]
Closing this, as for now we won't do anythin about this.
